name: flutter_flow
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: ^5.0.1
  get_it: ^7.2.0
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  bloc_concurrency: ^0.2.0
  injectable: ^1.5.3
  shared_preferences: ^2.0.15
  hydrated_bloc: ^8.1.0
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: 5.0.2
  build_runner:
  json_serializable: ^6.3.2

flutter:
  uses-material-design: true
